name: Template Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  repo-sync:
    if: github.repository != 'FBS93/embedded_workbench'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: FBS93/embedded_workbench
          upstream_branch: main
          pr_labels: template_sync
          target_gh_token: ${{ secrets.TEMPLATE_SYNC_PAT }}
